apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
        - name: snake-game
          image: yash5090/snake-game:latest # Replace with the actual image tag
          imagePullPolicy: Always
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
